<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Laporan Penjualan</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .info {
            margin-bottom: 20px;
        }
        .summary {
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Laporan Penjualan</h1>
    </div>
    
    <div class="info">
        <p><strong>Periode:</strong> {{ $filters['start_date'] }} s.d {{ $filters['end_date'] }}</p>
        <p><strong>Tipe:</strong> {{ ucfirst($filters['type']) }}</p>
        <p><strong>Dicetak oleh:</strong> {{ $user }}</p>
        <p><strong>Tanggal cetak:</strong> {{ $now }}</p>
    </div>
    
    <div class="summary">
        <h3>Summary</h3>
        <table>
            <tr>
                <td>Total Transaksi</td>
                <td>:</td>
                <td>{{ $summary['total_transactions'] }}</td>
            </tr>
            <tr>
                <td>Total Penjualan</td>
                <td>:</td>
                <td>{{ $summary['total_sales'] }}</td>
            </tr>
            <tr>
                <td>Total Pendapatan</td>
                <td>:</td>
                <td>Rp {{ number_format($summary['total_revenue'], 2, ',', '.') }}</td>
            </tr>
        </table>
    </div>
    
    <h3>Detail Laporan</h3>
    <table>
        <thead>
            <tr>
                <th>Periode</th>
                <th>Jumlah Transaksi</th>
                <th>Jumlah Produk Terjual</th>
                <th>Pendapatan</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData as $data)
            <tr>
                <td>{{ $data->date ?? $data['date'] }}</td>
                <td>{{ $data->transaction_count ?? $data['transaction_count'] }}</td>
                <td>{{ $data->total_quantity ?? $data['total_quantity'] }}</td>
                <td>Rp {{ number_format($data->total_revenue ?? $data['total_revenue'], 2, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="footer">
        <p>Generated by Toko Sayur System</p>
    </div>
</body>
</html>